# Generated by Django 5.0.3 on 2024-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_razorpayorder_item_price_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rp_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rp_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rp_payment_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
