# Generated by Django 5.0.3 on 2024-03-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_rp_order_id_order_rp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayorder',
            name='rp_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='rp_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='rp_payment_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
